### ISSUE TITLE
Support HPKP violations

### ISSUE THREAD

**Issue by reedloden** [skbkontur/csp_reporter#1]
Wonder if it would be possible to make this more generic so that it could be a collector for both CSP reports and HPKP reports (https://tools.ietf.org/html/rfc7469#section-3).

**Comment by beevee** [comment]
OK, why not. I'll look into this next weekend, or you can provide a pull request, if you like.

**Comment by beevee** [comment]
Done.

**Comment by reedloden** [comment]
Thanks!

**Comment by beevee** [comment]
Note that a separate URL is used for HPKP violations.

`/` or `/csp` for CSP
`/pkp` for HPKP
